### ISSUE TITLE
Encoding question

### ISSUE THREAD

**Issue by Zac91281** [Hakanaou/deepLuna#16]
Sorry to bother you again, and for the dumb question too; but is there a way to have the encoding supported for other languages? I was testing translations in my native language - which makes a lot of use of commas and accents -  however, when executed the letters are always distorted since the format is not supported

**Comment by Hakanaou** [comment]
When you say distorted, is it in game or in deepLuna? To which language are you translating?
The encoding is UTF-8, which should include most of usual characters from many languages.

**Comment by Zac91281** [comment]
In the game, I'm translating to portuguese. 
![image](https://user-images.githubusercontent.com/91568228/135762990-094960b3-a3e9-414c-84f6-2df1ee77b1ae.png)
Would it be a font issue then? Is there a way to solve/change it somehow?

**Comment by Hakanaou** [comment]
Unfortunately, this is a very complex issue, called kerning: this has to do that in Japanese, all letters have the same width while this is not the case in many other languages. This will mess up the width of letters and in particular when there are special characters.
We couldn't solve this problem in our team for the moment, and we played with fonts - this is what I would recommend you to do also, maybe you can mitigate a bit the problem with this.

**Comment by Zac91281** [comment]
I see, thank you! It shed some light on that question at least!

**Comment by CloverMoonTL** [comment]
![unknown](https://user-images.githubusercontent.com/90000241/135763302-c5c3bdb0-9bf7-4afa-88cf-8e7e5be4a559.png)
The best thing to do is to change some kanjis to look like your regional letters in the font, and use them instead of those letters. Kanjis have the same width as normal letters I believe. This is screenshot from the game with font that supports regional letters, but you can see that they take more space.

**Comment by Zac91281** [comment]
Thank you man, I'm going to try that!

**Comment by CloverMoonTL** [comment]
![image](https://user-images.githubusercontent.com/90000241/135765630-05f2bd0e-eb37-493c-9311-4d6d52b95ebf.png)
I tried what I described but it's not working. Every character that is more than 2 bytes renders wider, including kanjis. 
![image](https://user-images.githubusercontent.com/90000241/135765870-4efb315d-1f77-4638-a763-048ac0bd31be.png)
![image](https://user-images.githubusercontent.com/90000241/135765884-cebae817-83ad-475d-bf79-86b5df2bc206.png)
![image](https://user-images.githubusercontent.com/90000241/135765897-bcfd32ae-3cbc-48b3-be0a-42d60f52d6b3.png)

There is need to check every symbols and how they render. For now only $%&_~[]\ seem to be replaceable.

**Comment by CloverMoonTL** [comment]
![unknown](https://user-images.githubusercontent.com/90000241/135810542-0995149d-52d3-4b64-bcf3-1eb6f34b5d8b.png)
![image](https://user-images.githubusercontent.com/90000241/135810714-36bfd04b-0331-42b6-a5fb-a0ac9f873811.png)
Works now perfectly for polish, but I think portuguese have more letters that need to be inserted. In this case, you can sacrifice numbers and write them with words. (or move them to kanji section, they will look different but it would be necessary for letters). 
In red I shown which symbols you can swap with letters. The rest are needed for game code to work, or take double space.

**Comment by Hakanaou** [comment]
@Zac91281 I added today a new functionality that allows you to automatically do the replacements suggested by @CloverMoonTL - before clicking on insert, just check "Swap characters", and in the new window that opens input your pair of characters to exchange (one by line) in the form `old_char,new_char` where `old_char` is the character to replace by `new_char`. Finally click on "OK" (your replacement table will be saved and you won't have to redo this).
This just does the actual replacement to not do it by hand, but for the font tinkering procedure you still have to do it yourself.
If everything else is fine with you for the moment, tell me please so that I can close this issue.

**Comment by Zac91281** [comment]
That was it, I downloaded it wrongly, all perfect now! Thank you deeply for all your help!!

**Comment by Hakanaou** [comment]
Perfect! Then I'm closing the issue.
