### ISSUE TITLE
Injection Error

### ISSUE THREAD

**Issue by Sji27** [Hakanaou/deepLuna#31]
Hello. Sometimes get that error on text injection 
![image](https://user-images.githubusercontent.com/96915190/147825914-b7cc976f-c238-437c-bf73-56d229a3f38b.png)
Is that something i can avoid?

**Comment by rschlaikjer** [comment]
This assertion is firing because the script line it is trying to ingest contains a `>` (and end-ruby control code) without the associated open code. These inserted lines look like gibberish - 
> D&ed mq >qmbm pq&jm edv+ jb&fj&.

Is this really the text you are trying to inject?

**Comment by Sji27** [comment]
So, i need to change all ">"   Yes, text. Our alphabet has slightly more characters than yours. So we had to resort to replacing some characters to display correctly.

**Comment by rschlaikjer** [comment]
Ah, I see. Yes, I would advise against using the `<|>@` characters, since these are actually used by the game engine. The first three are used to display ruby text (the small text on top of words, e.g. `<bottom text|top text>`, and the @ symbol is used to toggle between fonts using the `@g` control code (arc d3).
