### ISSUE TITLE
script injection error

### ISSUE THREAD

**Issue by cuobai** [Hakanaou/deepLuna#7]
an error occured when i try to inject the script
![圖片](https://user-images.githubusercontent.com/74899300/132962985-e6b34bd0-b62b-4cda-a952-543db003f003.png)

**Comment by cuobai** [comment]
I find the problem. 
the error occured when I translated 051:246 and try to inject it.
is the text too long?
![圖片](https://user-images.githubusercontent.com/74899300/132974172-03789eb7-8fa4-4b16-97c1-cee3c02a19f6.png)

**Comment by Hakanaou** [comment]
That definitely has nothing to do with the length of the string - this part was already injected with translation several times in the game without problems.
It might be something with the translation sentence itself, it looks like the script sees it as a boolean instead of the string that corresponds to the sentence, which is weird.
Could you please send me the table.txt file that you have in your folder (don't forget to add deepLuna before the translation line that's failing)? It's the database file, I'm going to try to debug this.

**Comment by cuobai** [comment]
I'm trying to do chinese translation. (just for myself)
here is my table.txt.
[table.txt](https://github.com/Hakanaou/deepLuna/files/7154007/table.txt)

**Comment by Hakanaou** [comment]
Please download the new version of deepLuna, the bug should've been fixed. Tell me if this is okay, so I can close the issue.

**Comment by cuobai** [comment]
It's okay! Thanks you.

**Comment by Hakanaou** [comment]
Perfect! I'm closing this now.
